ESTAGIOS = (('Pioneira', 'Pioneira'),
            ('Secundária Inicial', 'Secundária Inicial'),
            ('Secundária Tardia', 'Secundária Tardia'),
            ('Umbrófila', 'Umbrófila'),
            ('Secundária', 'Secundária'),
            ('Climácica', 'Climácica'))

STATUS = (('Ativo', 'Ativo'), ('Inativo', 'Inativo'))

ESTADOS = (('AC', 'AC'),
           ('AL', 'AL'),
           ('AP', 'AP'),
           ('AM', 'AM'),
           ('BA', 'BA'),
           ('CE', 'CE'),
           ('DF', 'DF'),
           ('ES', 'ES'),
           ('GO', 'GO'),
           ('MA', 'MA'),
           ('MG', 'MG'),
           ('MT', 'MT'),
           ('MS', 'MS'),
           ('PA', 'PA'),
           ('PE', 'PE'),
           ('PB', 'PB'),
           ('PI', 'PI'),
           ('PR', 'PR'),
           ('RJ', 'RJ'),
           ('RN', 'RN'),
           ('RR', 'RR'),
           ('RS', 'RS'),
           ('RO', 'RO'),
           ('SC', 'SC'),
           ('SE', 'SE'),
           ('SP', 'SP'),
           ('TO', 'TO'))