# Generated by Django 3.0.3 on 2020-10-08 21:54

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Especie',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=1000)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='FormacaoFlorestal',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=500)),
                ('dominio', models.CharField(choices=[('amazonico', 'Amazonia'), ('mata_atlantica', 'Inativo'), ('mata_atlantica', 'Mata Atlantica'), ('caatinga', 'Caatinga'), ('cerrado', 'Cerrado'), ('pantanal', 'Pantanal'), ('pradarias', 'Pradarias'), ('', '')], default='', max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Registro',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False)),
                ('estagio', models.CharField(choices=[('pioneira', 'Pioneira'), ('secundaria_inicial', 'Secundaria Inicial'), ('secundaria_tardia', 'Secundaria Tardia'), ('umbrofila', 'Umbrofila'), ('secundaria', 'Secundaria')], max_length=50)),
                ('estado', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MT', 'MT'), ('MS', 'MS'), ('PA', 'PA'), ('PE', 'PE'), ('PB', 'PB'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RR', 'RR'), ('RS', 'RS'), ('RO', 'RO'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=50)),
                ('status', models.CharField(choices=[('active', 'Ativo'), ('inactive', 'Inativo')], max_length=15)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('especie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sucecoapp.Especie')),
                ('formacao_florestal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='sucecoapp.FormacaoFlorestal')),
            ],
        ),
    ]
