# Generated by Django 3.0.3 on 2020-10-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sucecoapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='referencia',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
