# Generated by Django 3.0.3 on 2020-10-09 00:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucecoapp', '0002_registro_referencia'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registro',
            name='especie',
        ),
        migrations.DeleteModel(
            name='Especie',
        ),
    ]
