# Generated by Django 3.0.3 on 2020-10-09 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sucecoapp', '0003_auto_20201009_0058'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Registro',
        ),
    ]
