# Generated by Django 3.2.16 on 2022-12-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forest',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500, unique=True)),
                ('domain', models.CharField(choices=[('Amazonia', 'Amazonia'), ('Mata Atlantica', 'Mata Atlantica'), ('Caatinga', 'Caatinga'), ('Cerrado', 'Cerrado'), ('Pantanal', 'Pantanal'), ('Pradarias', 'Pradarias'), ('', '')], max_length=100)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, max_length=15)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
