# Generated by Django 3.0.3 on 2020-10-09 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='estagio',
            field=models.CharField(choices=[('pioneira', 'Pioneira'), ('secundaria_inicial', 'Secundária Inicial'), ('secundaria_tardia', 'Secundária Tardia'), ('umbrofila', 'Umbrófila'), ('secundaria', 'Secundária')], max_length=50),
        ),
        migrations.AlterField(
            model_name='registro',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', max_length=15),
        ),
    ]
