# Generated by Django 3.0.3 on 2020-10-09 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0002_auto_20201009_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registro',
            name='estagio',
            field=models.CharField(choices=[('Pioneira', 'Pioneira'), ('Secundária Inicial', 'Secundária Inicial'), ('Secundária Tardia', 'Secundária Tardia'), ('Umbrófila', 'Umbrófila'), ('Secundária', 'Secundária')], max_length=50),
        ),
    ]
