# Generated by Django 3.0.3 on 2020-10-10 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registros', '0003_auto_20201009_2055'),
    ]

    operations = [
        migrations.AddField(
            model_name='registro',
            name='detalhes',
            field=models.CharField(default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='registro',
            name='estagio',
            field=models.CharField(choices=[('Pioneira', 'Pioneira'), ('Secundária Inicial', 'Secundária Inicial'), ('Secundária Tardia', 'Secundária Tardia'), ('Umbrófila', 'Umbrófila'), ('Secundária', 'Secundária'), ('Climácica', 'Climácica')], max_length=50),
        ),
    ]
