# Generated by Django 3.2.16 on 2022-12-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Reference',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('publication', models.CharField(default='', max_length=1000)),
                ('url', models.CharField(default='', max_length=1000)),
                ('status', models.CharField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, max_length=15)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
            ],
        ),
    ]
