# Generated by Django 3.0.3 on 2020-10-09 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='nome',
            field=models.CharField(help_text='Espécie', max_length=1000),
        ),
        migrations.AlterField(
            model_name='especie',
            name='status',
            field=models.CharField(choices=[('Ativo', 'Ativo'), ('Inativo', 'Inativo')], default='Ativo', help_text='Status', max_length=15),
        ),
    ]
