# Generated by Django 3.0.3 on 2020-10-09 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('especies', '0002_auto_20201009_1407'),
    ]

    operations = [
        migrations.AlterField(
            model_name='especie',
            name='nome',
            field=models.CharField(help_text='Espécie', max_length=1000, unique=True),
        ),
    ]
