# Generated by Django 3.2.16 on 2022-12-13 00:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('reference', '0001_initial'),
        ('species', '0001_initial'),
        ('forest', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('stage', models.CharField(choices=[('Pioneira', 'Pioneira'), ('Secundária Inicial', 'Secundária Inicial'), ('Secundária Tardia', 'Secundária Tardia'), ('Umbrófila', 'Umbrófila'), ('Secundária', 'Secundária'), ('Climácica', 'Climácica')], max_length=50)),
                ('state', models.CharField(choices=[('AC', 'AC'), ('AL', 'AL'), ('AP', 'AP'), ('AM', 'AM'), ('BA', 'BA'), ('CE', 'CE'), ('DF', 'DF'), ('ES', 'ES'), ('GO', 'GO'), ('MA', 'MA'), ('MG', 'MG'), ('MT', 'MT'), ('MS', 'MS'), ('PA', 'PA'), ('PE', 'PE'), ('PB', 'PB'), ('PI', 'PI'), ('PR', 'PR'), ('RJ', 'RJ'), ('RN', 'RN'), ('RR', 'RR'), ('RS', 'RS'), ('RO', 'RO'), ('SC', 'SC'), ('SE', 'SE'), ('SP', 'SP'), ('TO', 'TO')], max_length=50)),
                ('latitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=16, max_digits=22, null=True)),
                ('status', models.CharField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, max_length=15)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('forest', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='forest.forest')),
                ('reference', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='reference.reference')),
                ('species', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='species.species')),
            ],
        ),
    ]
