# Generated by Django 3.0.3 on 2020-10-09 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formacaoflorestal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formacaoflorestal',
            name='dominio',
            field=models.CharField(choices=[('Amazonia', 'Amazonia'), ('Mata Atlantica', 'Mata Atlantica'), ('Caatinga', 'Caatinga'), ('Cerrado', 'Cerrado'), ('Pantanal', 'Pantanal'), ('Pradarias', 'Pradarias'), ('', '')], max_length=100),
        ),
        migrations.AlterField(
            model_name='formacaoflorestal',
            name='nome',
            field=models.CharField(max_length=500, unique=True),
        ),
    ]
