# Generated by Django 3.2.16 on 2022-12-13 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('scientific_name', models.CharField(help_text='Species', max_length=1000, unique=True)),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('status', models.CharField(choices=[(1, 'Active'), (0, 'Inactive')], default=1, help_text='Status', max_length=15)),
            ],
            options={
                'ordering': ['scientific_name'],
            },
        ),
    ]
